image: node:latest

before_script:
  - npm install -g truffle
  - npm install

stages:
  - lint
  - test_solidity

run_js_linter:
  stage: lint
  script:
    - truffle compile
    - npm run lint

run_solidity_tests:
  stage: test_solidity
  script:
    - echo "TODO - Execute Solidity Tests"
